"""Initial schema

Revision ID: 0ca288b4bb46
Revises: 
Create Date: 2026-07-30 10:39:30.505422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca288b4bb46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('supports_chat', sa.Boolean(), nullable=False),
    sa.Column('supports_functions', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_audio', sa.Boolean(), nullable=False),
    sa.Column('supports_embeddings', sa.Boolean(), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('tokens_per_minute', sa.Integer(), nullable=True),
    sa.Column('input_price', sa.Float(), nullable=False),
    sa.Column('output_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=1000), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('name', name=op.f('uq_models_name'))
    )
    op.create_index('idx_models_available', 'models', ['available'], unique=False)
    op.create_index('idx_models_chat', 'models', ['supports_chat'], unique=False)
    op.create_index('idx_models_default', 'models', ['is_default'], unique=False)
    op.create_index('idx_models_enabled', 'models', ['enabled'], unique=False)
    op.create_index('idx_models_functions', 'models', ['supports_functions'], unique=False)
    op.create_index('idx_models_name', 'models', ['name'], unique=False)
    op.create_index('idx_models_provider', 'models', ['provider'], unique=False)
    op.create_index('idx_models_vision', 'models', ['supports_vision'], unique=False)
    op.create_table('tools',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('sandboxed', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('built_in', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('supported_languages', sa.JSON(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('average_runtime', sa.Float(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools')),
    sa.UniqueConstraint('name', name=op.f('uq_tools_name'))
    )
    op.create_index('idx_tool_builtin', 'tools', ['built_in'], unique=False)
    op.create_index('idx_tool_category', 'tools', ['category'], unique=False)
    op.create_index('idx_tool_enabled', 'tools', ['enabled'], unique=False)
    op.create_index('idx_tool_healthy', 'tools', ['healthy'], unique=False)
    op.create_index('idx_tool_name', 'tools', ['name'], unique=False)
    op.create_index('idx_tool_permission', 'tools', ['permission'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('execution_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_model', 'audit_logs', ['model_name'], unique=False)
    op.create_index('idx_audit_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('idx_audit_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('idx_audit_status', 'audit_logs', ['status_code'], unique=False)
    op.create_index('idx_audit_tool', 'audit_logs', ['tool_name'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('repository_url', sa.String(length=1000), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('slug', name=op.f('uq_projects_slug'))
    )
    op.create_table('chats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('conversation_metadata', sa.JSON(), nullable=False),
    sa.Column('context_files', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_chats_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_index('idx_chat_archived', 'chats', ['archived'], unique=False)
    op.create_index('idx_chat_model', 'chats', ['model_name'], unique=False)
    op.create_index('idx_chat_pinned', 'chats', ['pinned'], unique=False)
    op.create_index('idx_chat_project', 'chats', ['project_id'], unique=False)
    op.create_index('idx_chat_provider', 'chats', ['provider'], unique=False)
    op.create_index('idx_chat_user', 'chats', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('processing_node', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('causation_id', sa.String(length=100), nullable=True),
    sa.Column('workflow_id', sa.String(length=100), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_events_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('idx_event_aggregate', 'events', ['aggregate_id'], unique=False)
    op.create_index('idx_event_correlation', 'events', ['correlation_id'], unique=False)
    op.create_index('idx_event_processed', 'events', ['processed'], unique=False)
    op.create_index('idx_event_project', 'events', ['project_id'], unique=False)
    op.create_index('idx_event_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_event_user', 'events', ['user_id'], unique=False)
    op.create_index('idx_event_workflow', 'events', ['workflow_id'], unique=False)
    op.create_table('memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_access_score', sa.Float(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('memory_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_memories_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index('idx_memory_archived', 'memories', ['archived'], unique=False)
    op.create_index('idx_memory_category', 'memories', ['category'], unique=False)
    op.create_index('idx_memory_importance', 'memories', ['importance'], unique=False)
    op.create_index('idx_memory_project', 'memories', ['project_id'], unique=False)
    op.create_index('idx_memory_type', 'memories', ['memory_type'], unique=False)
    op.create_index('idx_memory_user', 'memories', ['user_id'], unique=False)
    op.create_table('metrics',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('metric_metadata', sa.JSON(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('workflow_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_metrics_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_metrics_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    op.create_index('idx_metric_category', 'metrics', ['category'], unique=False)
    op.create_index('idx_metric_model', 'metrics', ['model_name'], unique=False)
    op.create_index('idx_metric_name', 'metrics', ['name'], unique=False)
    op.create_index('idx_metric_project', 'metrics', ['project_id'], unique=False)
    op.create_index('idx_metric_provider', 'metrics', ['provider'], unique=False)
    op.create_index('idx_metric_tool', 'metrics', ['tool_name'], unique=False)
    op.create_index('idx_metric_type', 'metrics', ['metric_type'], unique=False)
    op.create_index('idx_metric_user', 'metrics', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('root_directory', sa.String(length=2048), nullable=True),
    sa.Column('current_branch', sa.String(length=255), nullable=False),
    sa.Column('last_commit', sa.String(length=64), nullable=True),
    sa.Column('git_status', sa.JSON(), nullable=False),
    sa.Column('indexed', sa.Boolean(), nullable=False),
    sa.Column('indexing_in_progress', sa.Boolean(), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('open_files', sa.JSON(), nullable=False),
    sa.Column('recent_files', sa.JSON(), nullable=False),
    sa.Column('active_file', sa.String(length=2048), nullable=True),
    sa.Column('workspace_metadata', sa.JSON(), nullable=False),
    sa.Column('last_scan_summary', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_workspaces_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_workspaces_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('path', name=op.f('uq_workspaces_path'))
    )
    op.create_index('idx_workspace_branch', 'workspaces', ['current_branch'], unique=False)
    op.create_index('idx_workspace_indexed', 'workspaces', ['indexed'], unique=False)
    op.create_index('idx_workspace_owner', 'workspaces', ['owner_id'], unique=False)
    op.create_index('idx_workspace_path', 'workspaces', ['path'], unique=False)
    op.create_index('idx_workspace_project', 'workspaces', ['project_id'], unique=False)
    op.create_index('idx_workspace_sync', 'workspaces', ['sync_status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('idx_chat_message_chat', 'chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_index('idx_chat_message_chat', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_workspace_sync', table_name='workspaces')
    op.drop_index('idx_workspace_project', table_name='workspaces')
    op.drop_index('idx_workspace_path', table_name='workspaces')
    op.drop_index('idx_workspace_owner', table_name='workspaces')
    op.drop_index('idx_workspace_indexed', table_name='workspaces')
    op.drop_index('idx_workspace_branch', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('idx_metric_user', table_name='metrics')
    op.drop_index('idx_metric_type', table_name='metrics')
    op.drop_index('idx_metric_tool', table_name='metrics')
    op.drop_index('idx_metric_provider', table_name='metrics')
    op.drop_index('idx_metric_project', table_name='metrics')
    op.drop_index('idx_metric_name', table_name='metrics')
    op.drop_index('idx_metric_model', table_name='metrics')
    op.drop_index('idx_metric_category', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('idx_memory_user', table_name='memories')
    op.drop_index('idx_memory_type', table_name='memories')
    op.drop_index('idx_memory_project', table_name='memories')
    op.drop_index('idx_memory_importance', table_name='memories')
    op.drop_index('idx_memory_category', table_name='memories')
    op.drop_index('idx_memory_archived', table_name='memories')
    op.drop_table('memories')
    op.drop_index('idx_event_workflow', table_name='events')
    op.drop_index('idx_event_user', table_name='events')
    op.drop_index('idx_event_type', table_name='events')
    op.drop_index('idx_event_project', table_name='events')
    op.drop_index('idx_event_processed', table_name='events')
    op.drop_index('idx_event_correlation', table_name='events')
    op.drop_index('idx_event_aggregate', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_chat_user', table_name='chats')
    op.drop_index('idx_chat_provider', table_name='chats')
    op.drop_index('idx_chat_project', table_name='chats')
    op.drop_index('idx_chat_pinned', table_name='chats')
    op.drop_index('idx_chat_model', table_name='chats')
    op.drop_index('idx_chat_archived', table_name='chats')
    op.drop_table('chats')
    op.drop_table('projects')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_tool', table_name='audit_logs')
    op.drop_index('idx_audit_status', table_name='audit_logs')
    op.drop_index('idx_audit_resource_type', table_name='audit_logs')
    op.drop_index('idx_audit_resource_id', table_name='audit_logs')
    op.drop_index('idx_audit_model', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tool_permission', table_name='tools')
    op.drop_index('idx_tool_name', table_name='tools')
    op.drop_index('idx_tool_healthy', table_name='tools')
    op.drop_index('idx_tool_enabled', table_name='tools')
    op.drop_index('idx_tool_category', table_name='tools')
    op.drop_index('idx_tool_builtin', table_name='tools')
    op.drop_table('tools')
    op.drop_index('idx_models_vision', table_name='models')
    op.drop_index('idx_models_provider', table_name='models')
    op.drop_index('idx_models_name', table_name='models')
    op.drop_index('idx_models_functions', table_name='models')
    op.drop_index('idx_models_enabled', table_name='models')
    op.drop_index('idx_models_default', table_name='models')
    op.drop_index('idx_models_chat', table_name='models')
    op.drop_index('idx_models_available', table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
