"""add llm_model

Revision ID: a95d7522b307
Revises: 0ca288b4bb46
Create Date: 2026-08-05 16:01:55.107957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95d7522b307'
down_revision: Union[str, Sequence[str], None] = '0ca288b4bb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('env_vars', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'env_vars')
    op.drop_column('projects', 'llm_model')
    # ### end Alembic commands ###
